

GET http://127.0.0.1:8012/api/method/stringerp.v1.api.hello_world
Content-Type: application/json

{
    "name": "ChatGPT"
}


### Test Hello World API (GET)
GET http://127.0.0.1:8012/api/method/stringerp.v1.api.hello_world?name=John
Content-Type: application/json


### Test Create SIV API (POST)
POST http://127.0.0.1:8014/api/method/stringerp.v1.api.create_siv
Content-Type: application/json

{
  "firstName": "STAFF",
  "phoneNumber": "EMP00011",
  "address1": "12",
  "guid": "68360e8c1f251",
  "salesmancode": "800",
  "deliverymancode": null,
  "customercode": "EMP00011",
  "salestype": "OT",
  "subtotal": 7.1,
  "SubTotalDiscount": 0,
  "shipping": 0,
  "nettotal": 7.1,
  "VATAmount": 0.71,
  "nettotalwithVAT": 7.81,
  "ispaid": 1,
  "billDate": "2025-04-18 00:42:11",
  "CRTime": "2025-04-18 00:42:11",
  "Remarks": "",
  "customerOrdernumber": "TTS-2500077",
  "Reupload": 0,
  "items": [
    {
      "barcode": "0001",
      "quantity": 1,
      "UnitPrice": "1.90000",
      "UnitDisc": "0.00000",
      "DiscTID": "DINEIN SECTION"
    },
    {
      "barcode": "0001",
      "quantity": 1,
      "UnitPrice": "2.50000",
      "UnitDisc": "0.00000",
      "DiscTID": "DINEIN SECTION"
    },
    {
      "barcode": "0001",
      "quantity": 1,
      "UnitPrice": "2.70000",
      "UnitDisc": "0.00000",
      "DiscTID": "DINEIN SECTION"
    }
  ],
  "payments": [
    {
      "POS_PAYCODE": 2,
      "CARDTYPE": "Cash",
      "CARDNO": "",
      "AMOUNT": 7.81
    }
  ]
}