

GET http://127.0.0.1:8012/api/method/stringerp.v1.api.hello_world
Content-Type: application/json

{
    "name": "ChatGPT"
}


### Test Hello World API (GET)
GET http://127.0.0.1:8012/api/method/stringerp.v1.api.hello_world?name=John
Content-Type: application/json


### Test Create SIV API (POST)
POST http://127.0.0.1:8002/api/method/stringerp.v1.api.create_siv
Content-Type: application/json

{
  "custname": "",
  "firstName": "Walkin Customer",
  "phoneNumber": "",
  "address1": "Flat: , Building: , Street: , Block: ",
  "guid": "69bfad62d5aw8d5",
  "salesmancode": "461",
  "altPhone": "",
  "deliverymancode": "",
  "customercode": "Walkin Customer",
  "onlineOrderId": "",
  "ordertype": "Invoice",
  "salestype": "DI",
  "subtotal": 2,
  "SubTotalDiscount": 0.2,
  "shipping": 0,
  "nettotal": 1.8,
  "VATAmount": 0.18,
  "nettotalwithVAT": 1.98,
  "ispaid": 1,
  "noOfPax": "1",
  "billDate": "2026-03-22 11:50:42",
  "tableno": "INDOOR T2-A",
  "CRTime": "2026-03-22 11:50:42",
  "Remarks": "",
  "Reupload": 0,
  "customerOrdernumber": "BTS-242600162",
  "items": [
    {
      "barcode": "258",
      "quantity": 1,
      "UnitPrice": 2,
      "rate": 2,
      "discrate": 0.2,
      "UnitDisc": 0.2,
      "DiscTID": "DINE IN"
    }
  ],
  "payments": [
    {
      "POS_PAYCODE": 2,
      "CARDTYPE": "CASH",
      "CARDNO": "",
      "AMOUNT": 1.98
    }
  ],
  "deliveryCharges": [],
  "posPayCode": 2,
  "posProfile": "TAWOOK-SEEF"
}


### Test Create SIV API (POST) with Debit Note

POST http://127.0.0.1:8002/api/method/stringerp.v1.api.create_siv
Content-Type: application/json

{
  "custname": "",
  "firstName": "Walkin Customer",
  "phoneNumber": "",
  "address1": "Flat: , Building: , Street: , Block: ",
  "guid": "69bfad62d5awf8d5",
  "salesmancode": "461",
  "altPhone": "",
  "deliverymancode": "",
  "customercode": "Walkin Customer",
  "onlineOrderId": "",
  "ordertype": "Debit note",
  "salestype": "DI",
  "subtotal": 2,
  "SubTotalDiscount": 0.2,
  "shipping": 0,
  "nettotal": 1.8,
  "VATAmount": 0.18,
  "nettotalwithVAT": 1.98,
  "ispaid": 1,
  "noOfPax": "1",
  "billDate": "2026-03-22 11:50:42",
  "tableno": "INDOOR T2-A",
  "CRTime": "2026-03-22 11:50:42",
  "Remarks": "",
  "Reupload": 0,
  "customerOrdernumber": "BTS-232600162",
  "items": [
    {
      "barcode": "258",
      "quantity": 0,
      "UnitPrice": 0,
      "rate":0,
      "discrate": 0,
      "UnitDisc": 0,
      "DiscTID": "DINE IN"
    }
  ],
  "payments": [
  ],
  "deliveryCharges": [],
  "posPayCode": 2,
  "posProfile": "ARAD"
}










### Test Create SIV API (POST) with multiple items and discounts
POST http://127.0.0.1:8002/api/method/stringerp.v1.api.create_siv
Content-Type: application/json

{ "erp_comp_name": "Mesk Holding B.S.C",
  "zatca_type": "B2C",
  "custname": "",
  "firstName": "Walkin Customer",
  "phoneNumber": "",
  "address1": "Flat: , Building: , Street: , Block: ",
  "guid": "69bd73se4esdw400a",
  "salesmancode": "553",
  "altPhone": "",
  "deliverymancode": "",
  "customercode": "Walkin Customer",
  "onlineOrderId": "",
  "ordertype": "Invoice",
  "salestype": "DI",
  "subtotal": 34,
  "SubTotalDiscount": 11.727,
  "shipping": 0,
  "nettotal": 22.273,
  "VATAmount": 2.227,
  "nettotalwithVAT": 24.5,
  "ispaid": 1,
  "noOfPax": "6",
  "billDate": "2026-03-20 21:25:21",
  "tableno": "INDOOR T2-A",
  "CRTime": "2026-03-20 21:25:21",
  "Remarks": "",
  "Reupload": 0,
  "customerOrdernumber": "BTS-s26s0q00d30",
  "items": [
    {
      "barcode": "BT0023",
      "quantity": 2,
      "UnitPrice": 4.54546,
      "rate": 2.27273,
      "discrate": 0,
      "UnitDisc": 0,
      "DiscTID": "DINE IN"
    },
    {
      "barcode": "BT0041",
      "quantity": 2,
      "UnitPrice": 4,
      "rate": 2,
      "discrate": 0,
      "UnitDisc": 0,
      "DiscTID": "DINE IN"
    },
    {
      "barcode": "BT0066",
      "quantity": 1,
      "UnitPrice": 6.36364,
      "rate": 6.36364,
      "discrate": 6.36364,
      "UnitDisc": 6.36364,
      "DiscTID": "ENTERTAINER"
    },
    {
      "barcode": "BT0066",
      "quantity": 1,
      "UnitPrice": 6.36364,
      "rate": 6.36364,
      "discrate": 0,
      "UnitDisc": 0,
      "DiscTID": "DINE IN"
    },
    {
      "barcode": "BT0103",
      "quantity": 1,
      "UnitPrice": 5.36364,
      "rate": 5.3634,
      "discrate": 0,
      "UnitDisc": 0,
      "DiscTID": "DINE IN"
    },
    {
      "barcode": "BT0103",
      "quantity": 1,
      "UnitPrice": 5.36364,
      "rate": 5.36364,
      "discrate": 5.36364,
      "UnitDisc": 5.36364,
      "DiscTID": "ENTERTAINER"
    },
    {
      "barcode": "BT0157",
      "quantity": 1,
      "UnitPrice": 2,
      "rate": 2,
      "discrate": 0,
      "UnitDisc": 0,
      "DiscTID": "DINE IN"
    }
  ],
  "payments": [
    {
      "POS_PAYCODE": 2,
      "CARDTYPE": "VISA",
      "CARDNO": "",
      "AMOUNT": 24.5
    }
  ],
  "deliveryCharges": [],
  "posPayCode": 2,
  "posProfile": "BAIT-SEEF"
}